config/routes.rb
Rails.application.routes.draw do
  resources :admins

  get 'admin/index'

  get 'special_page/about'

  resources :orders,:products

  root 'home#index'  
  get 'products/type/:producttype' => 'products#index', as: "products_type"
  get 'about' => 'special_page#about', as: "about"
  get 'login'  => "admins#index", as: "login"
  get 'logout' => "admins#destroy", as:"logout"
  get 'заявка' => "orders#new", as:"neworder"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
end

app/models/order.rb
# encoding: UTF-8
class Order < ActiveRecord::Base
	validates :name, presence: true,
                    length: { in: 2..40 }
    validates :surname, presence: true,
                    length: { in: 2..50 }      
    validates :phone, presence: true,
                    length: { in: 5..15 },
                    :format => { :with => /[0-9]/, :message => "Only numbers"}  
end

app/models/product.rb
class Product < ActiveRecord::Base
	mount_uploader :pictures, PictureUploader
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index 

  end
  def create
    @adminname = params.require(:admin).permit(:name)[:name]
    @adminpass = Admin.find_by(name: @adminname)[:password]
    if params.require(:admin).permit(:password)[:password] == @adminpass
      session[:admin] = true
      session[:password] = @adminpass
      flash[:notice] = "Successful Login" #Вы авторизированы
      redirect_to root_path
      else
        flash[:notice] = "Login has failed - check your name and password" #Неверный логин или пароль
        redirect_to login_path
      end
  end
  def destroy
    reset_session
    flash[:notice] = "You've logged out" #Вы вышли из системы
    redirect_to login_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :admin?

	protected

	def admin?
	 session[:admin] ? true : false
	end

	def authorize
	  unless admin?
	    redirect_to root_path
	    false
	  end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "main"
  def index
  end
end

app/controllers/orders_controller.rb
# encoding: UTF-8
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_filter :authorize, except: [:index, :show, :new, :create]
  # GET /orders
  # GET /orders.json
  def index
    if admin?
      @orders = Order.all
    else
      redirect_to neworder_path 
    end 
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        OrderMailer.order_email(@order).deliver_later
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :surname, :phone, :email, :comment)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
    before_filter :authorize, except: [:index, :show]
  # GET /products
  # GET /products.json
  def index
    if params[:producttype]
      @products = Product.where(producttype: params[:producttype])
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:producttype, :pictures, :brief, :description, :price)
    end
end

app/controllers/special_page_controller.rb
class SpecialPageController < ApplicationController
  def about
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def asset_exists?(path)
		pathname = Rails.application.assets.resolve(path)
		return !!pathname # double-bang turns String into boolean
	rescue Sprockets::FileNotFound
		return false
end 
def title(page_title)
  content_for(:title) { page_title }
end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/special_page_helper.rb
module SpecialPageHelper
end

app/views/admins/_form.html.haml
= form_for :admin, url: admins_path do |f|
  = f.text_field :name
  = f.password_field :password
  = f.submit("Войти", class:"blueButton")

app/views/admins/edit.html.haml
%h1 Editing admin

= render 'form'

= link_to 'Show', @admin
\|
= link_to 'Back', admins_path

app/views/admins/index.html.haml
-if flash[:notice] 
  %p#notice= notice
%section.content
  .cWrapper
    .bsTitle 
      Авторизация
    .wrapper.contentBox
      .cbContent.noinNav  
        -if admin?
          %h2 Вы уже авторизированы
        -else
          = render 'form'
    .clear
      

app/views/admins/new.html.haml
%h1 New admin

= render 'form'

= link_to 'Back', admins_path

app/views/admins/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @admin.name
%p
  %b Password:
  = @admin.password

= link_to 'Edit', edit_admin_path(@admin)
\|
= link_to 'Back', admins_path

app/views/home/index.html.haml
- title "Главная"
-if flash[:notice]
  %p#notice= notice
%header.index.botWLine
  %a.logo{:href => root_path}
  .rightBox
    #sign
      %div.profile Позвоните нам
    %ul.userNav
      %li
        адрес: г.Рубцовск, ул.Щетинкина, 5
      %li
        т.: 89628147485
      %li.clearfix     
%section#slider
  .sliderWrap
    .item
      .sliderBox
        %h1
          \вкусные идеи
          %br для летнего меню
        %h2
          \С НОВЫМИ МОРЕПРОДУКТАМИ
          %br ОТ ГЛОБУС ГУРМЭ
        %a.goBuy.goBut{:href => "#"} к покупкам
      %img.sliderImg{:alt => "", :src => "#{asset_path('slide1.png')}"}/
    .item
      .sliderBox
        %h1
          \Какая-то вафельная
          %br туфта для Вас
        %h2
          \Фотойте еду для  истограма
          %br дома, хипстеры
        %a.goBuy.goBut{:href => "#"} к покупкам
      %img.sliderImg{:alt => "", :src => "#{asset_path('slide2.png')}"}/
%nav#inNav
  %ul
    %li
      %a{:href => products_path}
        %span Каталог
    %li
      %a{:href => about_path}
        %span Контакты
    %li
      %a{:href => neworder_path}
        %span Оставить заявку
%section#infoAbout.wrapper
  .item
    .iconIA1.iconIA
    .infoAboutText
      18 супермаркетов и 98 различных
      \минимаркетов одном месте
  .item
    .iconIA2.iconIA
    .infoAboutText
      \Покупаете не выходя из дома,
      \не тратя время на поезду. Лишь
      20 мин на выбор и заказ товара
  .item
    .iconIA3.iconIA
    .infoAboutText
      \Доставка в удобный для вас
      \день и время
  .item
    .iconIA4.iconIA
    .infoAboutText
      \Мы любим наших клиентов
      \и постоянно дарим им подарки
  .clear
.dirtyLine
%section.infoBlock.wrapper
  .item Сохраняются данные - адреса, список покупок, избранное и всегда можно повторить заказ
  .item При регистрации вы получаете приятный бонус в размере 400 рублей на ваш счет!
  .item Сохраняются данные - адреса, список покупок, избранное и всегда можно повторить заказ
  .item
    %a.blueButton{:href => neworder_path} Оставить заявку
  .clear
%section#lostInfo.wrapper
  .boxWrapper
    .abountUs
      .title О нас
      .text
        mySupermarket is a new type of supermarket that allows you to compare prices and shop online from the main UK retailers in one place. Our aim is to help you save time and money while giving you the best possible online shopping experience.
        %br
        %br
        We offer 2 types of shop: Groceries and Health  Beauty. All you have to do is select your favourite retailer - Tesco, ASDA, Sainsbury's, Waitrose, Ocado, Boots or Superdrug and start shopping!
        %br
        %br
        It's up to you how you use our site: You can order your basket online, print your basket as a shopping list and take it with you to your local supermarket or simply just compare different supermarket prices online.

app/views/layouts/_footer.html.haml
%footer
  .footerWrapper
    .leftFotterBox
      %a.logo{:href => "#"}
    .footerNav
      .fnItem
        .title Информация
        %ul
          %li
            %a{:href => "#"} О нас
          %li
            %a{:href => "#"} Безопасность
          %li
            %a{:href => "#"} Советы
          %li
            %a{:href => "#"} Карта сайта
          %li
            %a{:href => "#"} Помощь
          %li
            %a{:href => "#"} Контактная информация
      .fnItem
        .title Магазины
        %ul
          %li
            %a{:href => "#"} Глобус Гурме
          %li
            %a{:href => "#"} Перекресток
          %li
            %a{:href => "#"} Азбука Вкуса
          %li
            %a{:href => "#"} Алые Паруса
      .fnItem
        .title Дополнительно
        %ul
          %li
            %a{:href => "#"} Форум
          %li
            %a{:href => "#"} Обсуждения
          %li
            %a{:href => "#"} Аналитика
          %li
            %a{:href => "#"} Рецепты
      .clear
    .clear
    .copirate © GLOBO Market 2010-2012

app/views/layouts/_header.html.haml
%header.main
  .hWrap
    %a.logo{:href => root_path}
    .rightBox
      %ul.userNav
        %li
          %a{:href => root_path} Главная
        %li
          %a{:href => products_path} Каталог
        %li
          %a{:href => neworder_path} Оставить заявку
        %li
          %a{:href => about_path} О компании
    .clear

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=US-ASCII", "http-equiv" => "Content-Type"}/
    %title ЖарПечь
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    = yield
    = render 'layouts/footer'

app/views/layouts/main.html.haml
!!!
%html
  %head
    %title #{yield(:title)}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => false
    = csrf_meta_tags
  %body
    = yield
    = render 'layouts/footer'   

app/views/orders/_form.html.haml
= form_for @order, :html => {:class => 'userdata'} do |f|
  - if @order.errors.any?
    #error_explanation
      %h2= "#{pluralize(@order.errors.count, "error")} ошибок, которые мешают сохранить:"
      %ul
        - @order.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label(:name, class:"litleTitle")
    = f.text_field :name
  .field.clearfix
    = f.label(:surname, class:"litleTitle")
    = f.text_field :surname
  .field
    = f.label(:phone, class:"litleTitle")
    = f.text_field :phone
  .field
    = f.label(:email, class:"litleTitle")
    = f.text_field :email
  .field
    = f.label(:comment, class:"litleTitle")
    = f.text_area :comment
  .actions
    = f.submit('Сохранить', class:"blueButton")

app/views/orders/edit.html.haml
%h1 Editing order

= render 'form'

= link_to 'Show', @order
\|
= link_to 'Back', orders_path

app/views/orders/index.html.haml
%h1 Listing orders

%table
  %thead
    %tr
      %th Name
      %th Surname
      %th Phone
      %th Email
      %th Comment
      %th
      %th
      %th

  %tbody
    - @orders.each do |order|
      %tr
        %td= order.name
        %td= order.surname
        %td= order.phone
        %td= order.email
        %td= order.comment
        %td= link_to 'Show', order
        - if admin?
          %td= link_to 'Destroy', order, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/orders/new.html.haml
%section.content
  .cWrapper
    .bsTitle Новая заявка
    .wrapper.contentBox
      .cbContent.noinNav
        = render 'form'
    .clear

app/views/orders/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @order.name
%p
  %b Surname:
  = @order.surname
%p
  %b Phone:
  = @order.phone
%p
  %b Email:
  = @order.email
%p
  %b Comment:
  = @order.comment
- if admin?
  = link_to 'Edit', edit_order_path(@order)
  \|
= link_to 'Back', orders_path

app/views/products/_form.html.haml
= form_for @product, :html => {:class => 'userdata', :multipart => true} do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :producttype
    = f.number_field :producttype
  .field
    = f.file_field :pictures
  .field
    = f.label :brief
    = f.text_area :brief
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :price
    = f.text_field :price
  .actions
    = f.submit('Сохранить', class:"blueButton")

app/views/products/edit.html.haml
%section.content
  .cWrapper
    .bsTitle Редактирование продукта
    .wrapper.contentBox
      .cbContent.noinNav
        = render 'form'
        %a.blueButton.backbut{:href => product_path(@product)} Показать
        %a.blueButton.backbut{:href => products_path} Назад 
    .clear

app/views/products/index.html.haml
-if flash[:notice]
  %p#notice= notice
%section.content
  .cWrapper
    -if @products
      .cat
        - @products.each do |product|
          .catitem
            %a.imga{:href => product_path(product)}
              = image_tag product.pictures.url(:thumb) 
            .textbox
              %p
                = product.brief
              .pricebox
                #{product.price} руб.
              %a.blueButton.backbut{:href => product_path(product)} Подробнее
              - if admin?
                .adminbox
                  = link_to 'Редактировать', edit_product_path(product)
                  = link_to 'Удалить', product, :method => :delete, :data => { :confirm => 'Уверены?' }
            .clear       
    -else
      .cat
        #kotl.catitem
          %a.imga{:href => products_type_path(1)}
            %img
          .textbox
            %h1.title
              Отопительные котлы
            %p
              mySupermarket is a new type of supermarket that allows you to compare prices and shop online from the main UK retailers in one place. Our aim is to help you save time and money while giving you the best possible online shopping experience.
            %a.blueButton.backbut{:href => products_type_path(1)} Подробнее           
          .clear  
        #pech.catitem
          %a.imga{:href => products_type_path(2)}
            %img
          .textbox
            %h1.title
              Отопительные печи
            %p
              mySupermarket is a new type of supermarket that allows you to compare prices and shop online from the main UK retailers in one place. Our aim is to help you save time and money while giving you the best possible online shopping experience.
            %a.blueButton.backbut{:href => products_type_path(2)} Подробнее          
          .clear    
  - if admin?
    %a.blueButton.backbut{:href => new_product_path} Добавить продукт

app/views/products/new.html.haml
%section.content
  .cWrapper
    .bsTitle Новый продукт
    .wrapper.contentBox
      .cbContent.noinNav
        = render 'form'
        %a.blueButton.backbut{:href => products_path} Назад 
    .clear

app/views/products/show.html.haml
-if flash[:notice]
  %p#notice= notice
%section.content
  .cWrapper
    .cat
      .catitem
        %a.imga
          = image_tag @product.pictures.url(:thumb) 
        .textbox
          %p
            = @product.description
          .pricebox
            #{@product.price} руб.
          - if admin?
            .adminbox
              = link_to 'Редактировать', edit_product_path(@product)
              = link_to 'Удалить', @product, :method => :delete, :data => { :confirm => 'Уверены?' }
        .clear  
%a.blueButton.backbut{:href => products_type_path(@product.producttype)} Назад

app/views/special_page/about.html.haml
- title "Главная"
-if flash[:notice]
  %p#notice= notice
%section.content
  .cWrapper
    .cat
      .textbox
        %h1.title
          О компании
        %p
          mySupermarket is a new type of supermarket that allows you to compare prices and shop online from the main UK retailers in one place. Our aim is to help you save time and money while giving you the best possible online shopping experience. 
      .textbox
        %h1.title
          Еще раздел 
        %p
          mySupermarket is a new type of supermarket that allows you to compare prices and shop online from the main UK retailers in one place. Our aim is to help you save time and money while giving you the best possible online shopping experience.                     
    .clear